### PR TITLE
Refactoring Stream concept useful for podcast applications

### PR DESCRIPTION
**Pull request by ppalazon**
Hi, I use MPDroid with an podcast application. And I would like to add a mp3 podcast directly to MPD and play it. I reuse Stream concept, but I prefer to add to multiple playlist after added to current playlist.

I don't like to create special playlist for 'Stream' concept, and
I prefer to show up with others playlist.

If you like this change, please add to master branch.

Thanks in advance, and thanks you so much for this useful application

### CODE REVIEW

**Comment by abarisain** [comment]
Hello!

As you may have noticed, MPDroid is no longer active development, meaning that I don't also take time to really review the merge requests, something essential for merging them.

I really appreciate the contributions, but I think that you should either maintain your own fork, or collaborate with other people who sent pull requests here and coordinate to make MPDroid better.

Have a nice day,

**Comment by sludgefeast** [comment]
Hi!

Please take a look at the branch [develop](https://github.com/abarisain/dmix/tree/develop). There are numerous improvements. In case of a refactoring your change should be done on this branch. I tried to cherry pick it, but your commits aren't really applicable to branch develop, because of many changes on affected files.

Please also take a look at my [develop](https://github.com/sludgefeast/MPDroid/tree/develop) branch - I'm currently working on some improvements.

regards

**Comment by abarisain** [comment]
@sludgefeast Would you mind if I add a reference to your repo in the readme and contribution.md (shows up when creating PRs or issues), or would that be unwanted attention? I feel kinda bad that people are wasting time sending me PRs that I will most definitely not merge

**Comment by sludgefeast** [comment]
@abarisain Yes, please do this. Maybe we get MPDroid reanimated.

**Pull request closed without merging**
