### PR TITLE
remove limpng warnings, using imagemagick convert tool strip function

### PR DESCRIPTION
**Pull request by fboldog**
Simple fix for remove this annoying warnings.

```
for i in xyz; do convert $i -strip $i; done
```

### CODE REVIEW

**Comment by abarisain** [comment]
@avuton ?
Btw where are the libpng warnings ?
I don't seem to be getting them



On Wed, May 20, 2015 at 7:36 AM -0700, "Ferenc Boldog" <notifications@github.com> wrote:












Simple fix for remove this annoying warnings.

for i in xyz; do convert $i -strip $i; done




You can view, comment on, or merge this pull request online at:


  https://github.com/abarisain/dmix/pull/719

Commit Summary

  remove limpng warnings, using imagemagick convert tool strip function


File Changes

  
    M
    MPDroid/src/main/res/drawable-hdpi/checkbox_off.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/checkbox_on.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_action_volume_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_appwidget_music_stop.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_media_repeat_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_media_repeat_on_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_media_shuffle_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_media_shuffle_on_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/ic_mp_move.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/no_cover_art.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/no_cover_art_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_control_disabled_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_control_focused_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_control_normal_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_control_pressed_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_primary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/scrubber_secondary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/spinner_default_holo_dark.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-hdpi/spinner_default_holo_light.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/appwidget_divider.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/checkbox_off.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/checkbox_on.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/no_cover_art.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/no_cover_art_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_control_disabled_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_control_focused_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_control_normal_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_control_pressed_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_primary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/scrubber_secondary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/spinner_default_holo_dark.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-mdpi/spinner_default_holo_light.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-nodpi/no_cover_art_big.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-nodpi/no_cover_art_light_big.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_action_volume_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_media_repeat_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_media_repeat_on_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_media_shuffle_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_media_shuffle_on_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/ic_mp_move.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/no_cover_art.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/no_cover_art_light.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_control_disabled_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_control_focused_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_control_normal_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_control_pressed_holo.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_primary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/scrubber_secondary_holo.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/spinner_default_holo_dark.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xhdpi/spinner_default_holo_light.9.png
    (0)
  
  
    M
    MPDroid/src/main/res/drawable-xxxhdpi/icon.png
    (0)
  


Patch Links:

  https://github.com/abarisain/dmix/pull/719.patch
  https://github.com/abarisain/dmix/pull/719.diff

**Comment by avuton** [comment]
Seems fine to me, as long as there's a response to your question.

**Comment by fboldog** [comment]
- fresh clone from develop branch
- ./gradlew build
```
........
:MPDroid:mergeClosedbitsDebugResources
AAPT err(173541495) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_appwidget_music_stop.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1853699419) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_control_pressed_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/checkbox_off.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(173541495) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_control_normal_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(723206573) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_media_shuffle_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(1868488761) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/spinner_default_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(671686409) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_primary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(528911786) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_media_repeat_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_secondary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_secondary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/spinner_default_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/no_cover_art.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/no_cover_art.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-nodpi/no_cover_art_light_big.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_control_disabled_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_action_volume_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_action_volume_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_control_normal_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_media_shuffle_on_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/no_cover_art_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/spinner_default_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_media_shuffle_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/checkbox_on.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/no_cover_art.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-nodpi/no_cover_art_big.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/spinner_default_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(33589713) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_primary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/spinner_default_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT err(33589713) : No Delegate set : lost message:/Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_control_focused_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_media_repeat_on_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/appwidget_divider.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/no_cover_art_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xxxhdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_media_shuffle_on_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_control_pressed_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_media_repeat_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/spinner_default_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/checkbox_off.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_secondary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_mp_move.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/ic_mp_move.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/ic_media_repeat_on_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_control_pressed_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/no_cover_art_light.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_control_focused_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_control_focused_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/checkbox_on.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-hdpi/scrubber_primary_holo.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-xhdpi/scrubber_control_disabled_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_control_normal_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT: /Volumes/REPOS/ext/dmix/MPDroid/src/main/res/drawable-mdpi/scrubber_control_disabled_holo.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
........
```

**Comment by fboldog** [comment]
related tools bug: https://code.google.com/p/android/issues/detail?id=77704

**Comment by avuton** [comment]
Pushed out to the ```develop``` branch. Thanks for the commit!

**Pull request closed without merging**
