### PR TITLE
layout-v21: Use correct colors for notifications

### PR DESCRIPTION
**Pull request by luk1337**
Screenshots:
notification: http://i.imgur.com/f9gFp5d.png
notification_big: http://i.imgur.com/7b81w8Q.png

### CODE REVIEW

**Comment by abarisain** [comment]
Hi and thanks for the pull request.

I'm not sure it's one we want to merge. Starting with lollipop, music apps seem to use dark notifications. I don't know what the rationale is, but here is a sccreenshot of play music and spotify:

screenshot_20151229-231941


Note that I haven't looked at the Android guidelines for that, so maybe it's explained there.

**Comment by luk1337** [comment]
Well, some other apps still use white notifications. PowerAmp for example: https://dl2.pushbulletusercontent.com/KliFzWhG4cup5EutgNoIW4cUL03O1p2p/Screenshot_20151230-000603.png

**Comment by abarisain** [comment]
I agree that it looks better (seriously, that screenshot I took looks like shit). I'll try to see if there's any recommendation

**Comment by luk1337** [comment]
Some music players also use notification background based on cover art color, Eleven from CyanogenMod for example.

**Comment by avuton** [comment]
So, I guess the pull request is rejected, but you're going to look into the layout colors?

**Comment by abarisain** [comment]
@avuton I'm pretty neutral about this one. I don't know if we want to switch to a white notification, or keep a dark one.  

That said, I don't think the PR should be merged because it hardcodes a lot of colors, which is fine if we hardcode the background, but not if we don't.

**Comment by abarisain** [comment]
Seeing how Android N has white notifications (even GPM uses one) and black notifications stick out like a sore thumb, this should be reworked (by us, possibly), but eventually this will be merged one way or another

**Pull request closed without merging**
