### PR TITLE
Add option "Add to Favorites" to now playing popup menu

### PR DESCRIPTION
**Pull request by nfnty**
Solves https://github.com/abarisain/dmix/issues/418

### CODE REVIEW

**Comment by abarisain** [comment]
Whoops, sorry for the time it took me to answer.  

I hate not merging PRs, since I really appreciate them, but I doubt it is a feature we want.  
The way it works is "simply" an alias to "Add To Playlist" -> "Favorite".  
I think that if we want this to work properly, we should do it more like GMPC does (Well, at least how I remember it does it) : Add a star somewhere, or at least a checkbox menu item, so that you can remove the song from favorites.  

Another issue with that implementation is that it will show "Add to Favorites" even if the song has already been added to that playlist. It is an issue with "Add to playlist" too, though.

**Comment by nfnty** [comment]
Sure, it's very simple and a star icon would be a better option. Is the feature to check if a song is present in a playlist implemented?

**Comment by abarisain** [comment]
Not sure :/

**Comment by avuton** [comment]
Rather than keep this PR open forever, I'm going to close it, *please* feel free to reopen or resubmit if you have improvements which you think would be acceptable.

**Comment by nfnty** [comment]
I'm a bit busy ATM, but will try to work something out in the coming weeks.

**Pull request closed without merging**
