### PR TITLE
push current track info to pebble

### PR DESCRIPTION
**Pull request by phryneas**
Hi,
this will display correct track information on pebble smartwatches.

I found some threads on reddit asking for this, so it seems I'm not the only one who was looking for that feature ;)

Hope you like it,
phry

### CODE REVIEW

**Comment by abarisain** [comment]
I didn't even know there was discussion about that on reddit!

I'm fine with adding that in the project. Notification with standard Media apis should take care of this though (maybe requires MusicBoss).

@avuton thoughts ?

**Comment by avuton** [comment]
At first look, it be much easier to send this Pebble [Intent] from the service. I'm surprised Pebble doesn't use RemoteControlClient. I could easily add this to the service, notification running would be required for now.

Back to the point, though, I could make the service run without the notification (we should probably do this anyhow, there's tons of complex code just to make it shutdown and startup), but that'll take a little bit.

**Comment by phryneas** [comment]
Well, I just didn't want to clutter existing code too much - just tell me where to add it and I'll happily do ;)

@reddit: not much, but there are three threads searching for a solution in /r/pebble and of the sounds of it, MPDroid is (was?) not working too well with MusicBoss, so I didn't even try that

**Comment by avuton** [comment]
@phryneas Maybe [MPDroidService.java:748](https://github.com/abarisain/dmix/blob/master/MPDroid/src/main/java/com/namelessdev/mpdroid/service/MPDroidService.java#L748) would be good? It's already setup to listen, so, we're talking a few LOC change, though, again, the notification has to be working. And the service doesn't reconnect (as it stands right now), so with those caveats in mind, this would probably be suitable.

**Comment by phryneas** [comment]
Argh xD

I already had been testing code there, but nothing happened, so I chose this other solution. Of course, I did not have that notification enabled... 

Will move it there - oh, and that notification looks great, by the way :+1:

**Comment by phryneas** [comment]
Okay, moved it over - did just a quick test, but it seems to work too - not just as immediate, but I think that's not really a problem.

**Comment by avuton** [comment]
OK, I'll rebase it pull it into abarisain:develop as soon as I get an opportunity.

**Comment by phryneas** [comment]
Great :)

**Comment by avuton** [comment]
Fixed via f951d04. Thanks!

**Comment by abarisain** [comment]
Great, thanks :)

**Pull request closed without merging**
