### PR TITLE
Follow different protocol redirect

### LINKED ISSUE #716: Local covers cannot be served over HTTPS
Hello,

There is no way to specifiy HTTPS as the protocol to use to retrieve cover images.

The following code, in `MPDroid/src/main/java/com/namelessdev/mpdroid/cover/LocalCover.java`, defines and uses only one possible `URL_PREFIX`.

```java
    private static final String URL_PREFIX = "http://";

    [...]

    public static String buildCoverUrl(String serverName, String musicPath, final String path,
            final String fileName) {

        if (musicPath.startsWith(URL_PREFIX)) {
            int hostPortEnd = musicPath.indexOf(URL_PREFIX.length(), '/');
            if (hostPortEnd == -1) {
                hostPortEnd = musicPath.length();
            }
            serverName = musicPath.substring(URL_PREFIX.length(), hostPortEnd);
            musicPath = musicPath.substring(hostPortEnd);
        }
        final Uri.Builder uriBuilder = Uri.parse(URL_PREFIX + serverName).buildUpon();
        appendPathString(uriBuilder, musicPath);
        appendPathString(uriBuilder, path);
        appendPathString(uriBuilder, fileName);

        final Uri uri = uriBuilder.build();
        return uri.toString();
    }
```

Would it be possible to handle HTTPS? This is the only reason my webserver is still running on port 80. :)

Thanks!

### PR DESCRIPTION
**Pull request by Kernald**
`HttpURLConnection` does not follow redirections to a different protocol. This commit follows such redirections in the `CoverManager` class. This fixes #716.

### CODE REVIEW

**Comment by abarisain** [comment]
Looks fine thanks. 

@avuton I'm ok to merge this if you are

**Comment by avuton** [comment]
Don't worry about me, I've moved on to using DLNA exclusively. Thanks!

**Comment by abarisain** [comment]
Thanks for the PR :)

**Comment by Kernald** [comment]
You're welcome, thanks for merging!

**Pull request merged**
